spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 0
mybatis:
  mapper-locations: classpath:/mapper/*.xml
