
package com.wl.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IJzcxWebService", targetNamespace = "http://webservice.com", wsdlLocation = "file:/C:/Users/Lang/Desktop/s_1200000900000_2108(2).wsdl")
public class IJzcxWebService
    extends Service
{

    private final static URL IJZCXWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException IJZCXWEBSERVICE_EXCEPTION;
    private final static QName IJZCXWEBSERVICE_QNAME = new QName("http://webservice.com", "IJzcxWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Lang/Desktop/s_1200000900000_2108(2).wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IJZCXWEBSERVICE_WSDL_LOCATION = url;
        IJZCXWEBSERVICE_EXCEPTION = e;
    }

    public IJzcxWebService() {
        super(__getWsdlLocation(), IJZCXWEBSERVICE_QNAME);
    }

    public IJzcxWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IJZCXWEBSERVICE_QNAME, features);
    }

    public IJzcxWebService(URL wsdlLocation) {
        super(wsdlLocation, IJZCXWEBSERVICE_QNAME);
    }

    public IJzcxWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IJZCXWEBSERVICE_QNAME, features);
    }

    public IJzcxWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IJzcxWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IJzcxWebServicePortType
     */
    @WebEndpoint(name = "IJzcxWebServiceHttpPort")
    public IJzcxWebServicePortType getIJzcxWebServiceHttpPort() {
        return super.getPort(new QName("http://webservice.com", "IJzcxWebServiceHttpPort"), IJzcxWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IJzcxWebServicePortType
     */
    @WebEndpoint(name = "IJzcxWebServiceHttpPort")
    public IJzcxWebServicePortType getIJzcxWebServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.com", "IJzcxWebServiceHttpPort"), IJzcxWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IJZCXWEBSERVICE_EXCEPTION!= null) {
            throw IJZCXWEBSERVICE_EXCEPTION;
        }
        return IJZCXWEBSERVICE_WSDL_LOCATION;
    }

}
