
package com.wl.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IJzcxWebServicePortType", targetNamespace = "http://webservice.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IJzcxWebServicePortType {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GK_JZCX_RKJCXXCX")
    @WebResult(name = "out", targetNamespace = "http://webservice.com")
    @RequestWrapper(localName = "GK_JZCX_RKJCXXCX", targetNamespace = "http://webservice.com", className = "com.webservice.GKJZCXRKJCXXCX")
    @ResponseWrapper(localName = "GK_JZCX_RKJCXXCXResponse", targetNamespace = "http://webservice.com", className = "com.webservice.GKJZCXRKJCXXCXResponse")
    public String gkJZCXRKJCXXCX(
            @WebParam(name = "in0", targetNamespace = "http://webservice.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://webservice.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://webservice.com")
                    String in2);

}
